---
title: "Factors"
format: html
number-sections: false
---
```{r}
library(tidyverse)
```

The exercises revisit our grades data:
```{r}
# Get rid of some duplicate rows!
grades <- read.csv("https://mac-stat.github.io/data/grades.csv") |> 
  distinct(sid, sessionID, .keep_all = TRUE)

# Check it out
head(grades)
```

We’ll explore the number of times each grade was assigned:
```{r}
grade_distribution <- grades |> 
  count(grade)

head(grade_distribution)
```

## Exercise 1: Changing Order

```{r}
# Check out a column plot of the number of times each grade was assigned during the study period
grade_distribution |> 
  ggplot(aes(x = grade, y = n)) +
    geom_col()
```

```{r}
# Construct a new column plot, manually reordering the grades from high (A) to low (NC) with “S” and “AU” at the end:
grade_distribution |>
  mutate(grade = fct_relevel(grade, c("A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "NC", "S", "AU"))) |>
  ggplot(aes(x = grade, y = n)) +
    geom_col()
```

```{r}
# Construct a new column plot, reordering the grades in ascending frequency (i.e. how often the grades were assigned):
grade_distribution |>
  mutate(grade = fct_reorder(grade, n)) |>
  ggplot(aes(x = grade, y = n)) +
    geom_col()
```

```{r}
# Construct a new column plot, reordering the grades in descending frequency (i.e. how often the grades were assigned):
grade_distribution |>
  mutate(grade = fct_reorder(grade, n, .desc = TRUE)) |>
  ggplot(aes(x = grade, y = n)) +
    geom_col()
```

## Exercise 2: Changing Factor Level Labels

```{r}
# It may not be clear what “AU” and “S” stand for. Construct a new column plot that renames these levels “Audit” and “Satisfactory”, while keeping the other grade labels the same and in a meaningful order:
grade_distribution |>
  mutate(grade = fct_relevel(grade, c("A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "NC", "S", "AU"))) |>
  mutate(grade = fct_recode(grade, "Satisfactory" = "S", "Audit" = "AU")) |>  # Multiple pieces go into the last 2 blanks
  ggplot(aes(x = grade, y = n)) +
    geom_col()
```

